apiVersion: v1
kind: Service
metadata:
  name: journey-lb
  labels:
    tier: backend
spec:
  type: LoadBalancer
  selector:
    app: nginx
    tier: backend
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
